apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.data.port.number }}
    targetPort: {{ .Values.data.port.number }}
    nodePort: {{ .Values.service.NodePort }}
  selector:
    app: {{ .Values.data.labels.app }}